<?php

// This file was generated by running "composer dump-env prod"

#return array (
#  'APP_ENV' => 'prod',
 # 'APP_SECRET' => 'ab4ca165c804faf28118306630692c17',
#  'APP_DEBUG' => '0',
#  'DATABASE_URL' => 'mysql://snryljie_Yacein:am3jc=z%@IO&@127.0.0.1:3306/snryljie_Atypik?serverVersion=8&charset=utf8mb4',
#);
