<?php

namespace ClasseBundle\Repository;

/**
 * Photo2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Photo2Repository extends \Doctrine\ORM\EntityRepository
{
}
