<?php

namespace ClasseBundle\Repository;

/**
 * PrisedevueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrisedevueRepository extends \Doctrine\ORM\EntityRepository
{
}
