<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcLeHe5\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcLeHe5/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerJcLeHe5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerJcLeHe5\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerJcLeHe5\srcApp_KernelDevContainer([
    'container.build_hash' => 'JcLeHe5',
    'container.build_id' => 'cb1f6a69',
    'container.build_time' => 1680775517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcLeHe5');
