<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \App\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'dateMessage', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'contexte', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'touser', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'habitat', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fromuser'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'dateMessage', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'contexte', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'touser', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'habitat', '' . "\0" . 'App\\Entity\\Message' . "\0" . 'fromuser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateMessage($dateMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateMessage', [$dateMessage]);

        return parent::setDateMessage($dateMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateMessage', []);

        return parent::getDateMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setContexte($contexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContexte', [$contexte]);

        return parent::setContexte($contexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getContexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContexte', []);

        return parent::getContexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setTouser(\App\Entity\User $touser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTouser', [$touser]);

        return parent::setTouser($touser);
    }

    /**
     * {@inheritDoc}
     */
    public function getTouser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTouser', []);

        return parent::getTouser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFromuser(\App\Entity\User $fromuser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFromuser', [$fromuser]);

        return parent::setFromuser($fromuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getFromuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFromuser', []);

        return parent::getFromuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabitat($habitat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabitat', [$habitat]);

        return parent::setHabitat($habitat);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitat', []);

        return parent::getHabitat();
    }

}
